services:
  zabbix-server-mysql:
    image: mariadb:10.6
    container_name: zabbix-server-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql/data
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - zabbix-ipv4

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: ${MARIADB_HOST_NAME}
      DB_SERVER_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - zabbix-server-mysql
    ports:
      - "${ZABBIX_PORT}:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
    networks:
      zabbix-ipv4:
        ipv4_address: 10.10.1.10

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - zabbix-server-mysql
      - zabbix-server
    environment:
      DB_SERVER_HOST: ${MARIADB_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_SERVER_HOST: ${ZABBIX_HOST_NAME}
      PHP_TZ: ${TIMEZONE}
    ports:
      - "${NGINX_PORT}:8080"
    volumes:
      - zabbix-web-data:/usr/share/zabbix
    networks:
      - zabbix-ipv4

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: ${ZABBIX_HOST_NAME}
      ZBX_SERVER_PORT: ${ZABBIX_PORT}
      ZBX_SERVER_ACTIVE: zabbix-server
    networks:
      - zabbix-ipv4

networks:
  zabbix-ipv4:
    ipam:
      config:
        - subnet: 10.10.1.0/24

volumes:
  mysql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:

