---

- name: Create directory for zabbix server
  ansible.builtin.file:
    path: "{{ deploy_zabbix_server_directory }}"
    state: directory
    mode: "0755"
    owner: 1000
    group: 1000
  when: not zabbix_project.stat.exists

- name: Get docker compose file to zabbix_project
  ansible.builtin.template:
    src: sources/docker-compose.yml.j2
    dest: "{{ deploy_zabbix_server_directory }}/docker-compose.yml"
    mode: "0755"
    owner: 1000
    group: 1000

- name: Get config file to zabbix_project
  ansible.builtin.template:
    src: sources/my.cnf.j2
    dest: "{{ deploy_zabbix_server_directory }}/my.cnf"
    mode: "0755"
    group: 1000
    owner: 1000

- name: Generate .env file
  ansible.builtin.template:
    src: environments/environment.j2
    dest: "{{ deploy_zabbix_server_directory }}/.env"
    mode: "0600"
    group: 1000
    owner: 1000
